### PR TITLE
basic Hebrew translation

### PR DESCRIPTION
**Pull request by shmuel-krakower**
Please note I wanted to push something rather than nothing so its partial for now.
I've used a female form as suggested, when referring the user or other users. I used the male form when referring to objects (assuming the object is a male) but it might be wrong. I.e. a Message is a female while a Button is a male.
There might be some mismatches or wrong translation. Only once someone look at the translated UI he can and figure out the context of the word. I guess it will be ongoing with others to continue and translate as they use it, not sure when and if I'll continue the work here...

### CODE REVIEW

**Comment by kajmagnus** [comment]
Hi Shmuel, thanks for reopening here. Can you please reply here and say that / if you agree to the CLA?

That is, the file `./docs/CLA-v2.txt` in the main repo: (not this `ty-cla` repo)
https://github.com/debiki/talkyard/blob/master/docs/CLA-v2.txt

Or, if you want to, you can follow the steps here: https://github.com/debiki/talkyard#contributing

**Comment by shmuel-krakower** [comment]
I agree to the CLA.

**Comment by kajmagnus** [comment]
Ok thanks :- )

I'll merge later today or tomorrow. New version upcoming later this week (is the plan).

**Comment by kajmagnus** [comment]
Merged, thanks! :- )

https://github.com/debiki/ty-cla/commit/8edba902ff83271084d276c13ad84806fc97fd14

(Hebrew will be included in the upcoming version — it got a bit delayed.)

**Comment by kajmagnus** [comment]
I added a comment about "time letters", e.g.  "3d" or "3h" as a short version of "3 days" or "3 hours":

https://github.com/debiki/ty-cla/commit/6575cc9c32da7c763b0f5a74edd27174cf9bbcb8

I'm curious about if that works in Hebrew

**Pull request merged**
