### PR TITLE
Added Germam email template translations.

### PR DESCRIPTION
**Pull request by saschazelzer**
I, Sascha Zelzer <sascha.zelzer@gmail.com>, agree to the Contributor License Agreement, docs/CLA-v2.txt.

### CODE REVIEW

**Comment by kajmagnus** [comment]
Hi Sascha, thanks for the PR, I'm trying out this now.

Sorry, can you please rebase on Master? The CLA, `docs/CLA-v2.txt` wasn't in this repo, only in the main repo, `debiki/talkyard`, but now I've copied it to here, too, in the main branch. (So if you rebase, the `docs/CLA-v2.txt` in the commit message, will refer to a file that actually exists.)

If you want to, you could have a look at the CLA again — the simplest way to do so, might be to run `sha1sum` and compare with the one in the `debiki/talkyard` repo (which you've read already) and you'll notice it's the same:

https://github.com/debiki/talkyard/blob/master/docs/CLA-v2.txt
https://github.com/debiki/ty-translations/blob/master/docs/CLA-v2.txt

***

I can include this in the upcoming release later this week.

**Comment by saschazelzer** [comment]
Hi, checked the CLA and rebased the PR on master. Thanks for the fast feedback.

**Comment by saschazelzer** [comment]
I force-pushed one more time, fixing a silly typo in the commit message.

**Comment by kajmagnus** [comment]
Thanks! I got this compiling now on localhost  (nice with type safe email templates :- ))

**Comment by kajmagnus** [comment]
This is now merged and included in the latest version, v0.2021.23. Thanks Sascha!

Let me know how it works for you?

**Pull request merged**
